---
language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements/dev.txt
cache: pip
notifications:
  email: false
jobs:
  include:
  - stage: tests
    script: pytest
  - script: pylint peralta.py
