version: '3'
services:
  peralta:
    build: .
    volumes:
    - $PWD:/code
    env_file: .env
  test:
    build: .
    env_file: .env
    volumes:
    - $PWD/tests:/code/tests
    command:
      pytest
