version: '3'
services:
  peralta:
    build: .
    volumes:
      - $PWD:/code
    env_file: .env
    depends_on:
      - mongo
  mongo:
    image: mongo:4.1
    ports:
      - "27017:27017"
  test:
    build: .
    env_file: .env
    volumes:
      - $PWD/tests:/code/tests
    command:
      pytest
